language: node_js

node_js:
  - 0.10

notifications:
  email:
    recipients:
      - yury@magic.io
      - victor@magic.io

    on_success: never
    on_failure: always

install:
  - make

script:
  - make test
